version: '3'

tasks:
  build:
    desc: "Compile the ynab-vault binary"
    sources:
      - '*.go'
      - '*.mod'
      - '*.sum'
    generates:
      - bin/ynab-vault
    cmds:
      - go build -o bin/ynab-vault main.go
    silent: true

  run:
    desc: "Fetch all budgets using YNAB Vault"
    silent: true
    deps:
      - build
    vars:
    cmds:
      - ./bin/ynab-vault --output budgets

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./... --fix
    silent: true

  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...
    silent: true

  clean:
    desc: "Remove built binary and budgets directory"
    cmds:
      - rm -rf bin
      - rm -rf budgets
    silent: true